FROM node:23.3-alpine3.20
WORKDIR /usr/local/apps/frontend

COPY package.json ./
RUN npm install && npm cache clean --force

COPY . ./

ARG VITE_APP_API_BASE_URL
ENV VITE_APP_API_BASE_URL=${VITE_APP_API_BASE_URL}

EXPOSE ${PORT}

CMD [ "npm", "start"]