FROM node:22-alpine
WORKDIR /usr/local/apps/frontend

COPY package.json ./
RUN npm install && npm cache clean --force
RUN npm install @rollup/rollup-linux-x64-musl

COPY . ./

ARG VITE_APP_API_BASE_URL
ENV VITE_APP_API_BASE_URL=${VITE_APP_API_BASE_URL}

EXPOSE ${PORT}

CMD [ "npm", "start"]