services:
  backend:
    build: ./backend
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    environment:
      - PORT=${NODE_DOCKER_PORT}
      - TOKEN=${TOKEN}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
      - DB_HOST=${MYSQL_HOST}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_TYPE=${MYSQL_TYPE}
    volumes:
      - ./backend:/usr/local/apps/backend
      - node_modules_back:/usr/local/apps/backend/node_modules
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_APP_API_BASE_URL=${CLIENT_API_BASE_URL}
    ports:
      - ${VITE_LOCAL_PORT}:${VITE_DOCKER_PORT}
    volumes:
      - ./frontend:/usr/local/apps/frontend
      - node_modules_front:/usr/local/apps/frontend/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql-data:
  node_modules_front:
  node_modules_back:


networks:
  app-network: